name: foraging

# TODO take inspiration from https://paulomarconi.github.io/blog/Foraging_Aggregation_V-rep_e-puck/
#     AND  https://github.com/Nikorasu/PyNAnts
#     AND  https://github.com/rmvanarse/swarm_tasks , https://www.youtube.com/watch?v=HZjE_zC4Yek
#     AND  https://github.com/patrick-mahnkopf/emergent-algorithms